// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA65moI6IjeVlaAEbgk1oCwyRRXTSJ21HA',
    appId: '1:1049234975862:web:58bf10645c87476d8e0357',
    messagingSenderId: '1049234975862',
    projectId: 'adota-facil-8c2b9',
    authDomain: 'adota-facil-8c2b9.firebaseapp.com',
    storageBucket: 'adota-facil-8c2b9.firebasestorage.app',
    measurementId: 'G-39KRB4BLKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDllrDEaaTEWI3mU5_E2I5qdXQ06GQLmF4',
    appId: '1:1049234975862:android:3a1d2a346001f2268e0357',
    messagingSenderId: '1049234975862',
    projectId: 'adota-facil-8c2b9',
    storageBucket: 'adota-facil-8c2b9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdaWt_r9fgquYYfdZoOMhw0JxsRckiP44',
    appId: '1:1049234975862:ios:a5e865fca3acb4818e0357',
    messagingSenderId: '1049234975862',
    projectId: 'adota-facil-8c2b9',
    storageBucket: 'adota-facil-8c2b9.firebasestorage.app',
    iosBundleId: 'com.example.adotaFacil',
  );
}
